# (a)

In [2]:
import numpy as np

In [17]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# (b)

In [11]:
identity = np.eye(4,3)

In [12]:
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

# c

In [ ]:
array = np.arange(10,20)

In [15]:
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
array.reshape(5,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

# (d)

In [22]:
array1 = np.array([1,2,3,41,2,3,4,"ram","shyam","ram","krishna","krishna"])

In [23]:
array1

array(['1', '2', '3', '41', '2', '3', '4', 'ram', 'shyam', 'ram',
       'krishna', 'krishna'], dtype='<U11')

In [24]:
np.unique(array1)

array(['1', '2', '3', '4', '41', 'krishna', 'ram', 'shyam'], dtype='<U11')